services:
  user_service:
    container_name: userService-container
    build:
      context: .
      dockerfile: user_service/Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./user_service:/app
    restart: unless-stopped
    command: ["python3", "app.py"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5001"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s  

  destination_service:
    container_name: destinationService-container
    build:
      context: .
      dockerfile: destination_service/Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./destination_service:/app
    restart: unless-stopped
    command: ["python3", "app.py"]
    depends_on:
      user_service:
        condition: service_healthy

  auth_service:
    container_name: authService-container
    build:
      context: .
      dockerfile: auth_service/Dockerfile
    ports:
      - "5003:5003"
    volumes:
      - ./auth_service:/app
    restart: unless-stopped
    command: ["python3", "app.py"]
    depends_on:
      user_service:
        condition: service_healthy

